-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 17:09:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema payroll_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payroll_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payroll_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `payroll_service` ;

-- -----------------------------------------------------
-- Table `payroll_service`.`employee_payroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payroll_service`.`employee_payroll` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Department` VARCHAR(150) NOT NULL,
  `basic_pay` FLOAT NOT NULL DEFAULT '5000000',
  `deductions` FLOAT NOT NULL DEFAULT '600000',
  `taxable_pay` FLOAT NOT NULL DEFAULT '700000',
  `income_tax` FLOAT NOT NULL DEFAULT '800000',
  `net_pay` FLOAT NOT NULL DEFAULT '90000',
  `Phone_number` VARCHAR(250) NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  `Gender` VARCHAR(10) NULL DEFAULT NULL,
  `start` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payroll_service`.`employee_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payroll_service`.`employee_department` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `EmpID` INT UNSIGNED NULL DEFAULT NULL,
  `DeptName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `EmpID` (`EmpID` ASC) VISIBLE,
  CONSTRAINT `employee_department_ibfk_1`
    FOREIGN KEY (`EmpID`)
    REFERENCES `payroll_service`.`employee_payroll` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
